projet: Database.o Protein.o Algorithm.o
	g++ Database.o Protein.o Algorithm.o projet.cpp -o projet 
Database.o: Database.cpp 
	g++ -c Database.cpp -o Database.o
Protein.o: Protein.cpp
	g++ -c Protein.cpp -o Protein.o
Algorithm.o: Algorithm.cpp
	g++ -c Algorithm.cpp -o Algorithm.o
clean: 
	rm -rf *.o
	
	
